apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: kubenews-pvc
  labels:
    app: kubenews-db
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
---
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: kubenews-pv
spec:
  storageClassName: slow
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate

