apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews-db
spec:
  selector:
    matchLabels:
      app: kubenews-db
  replicas: 1
  template:
    metadata:
      labels:
        app: kubenews-db
    spec:
      containers:
        - name: kubenews-db
          image: postgres:alpine3.18
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "1Gi"
              #cpu: "1000m"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: kubenewsdb-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: kubenewsdb-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubenewsdb-secrets
                key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data              
          ports:
          - containerPort: 5432
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: kubenews-pvc
      